name: audio_player
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter_sound: ^9.2.13
  path_provider: ^2.1.1
  lottie: ^2.7.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_styled_toast: ^2.2.1
  permission_handler: ^11.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:
  assets:
      - assets/image/
  uses-material-design: true
